#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'python'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.CFLAGS = ["/MTd"]
	conf.env.CXXFLAGS = ["/MTd"]
	conf.env.LINKFLAGS += ["Version.lib","WS2_32.lib","pathcch.lib","Advapi32.lib","Bcrypt.lib"]
	return

def build(bld):
	source = ['Programs/python.c']
	
	print(bld.env.LINKFLAGS)

	includes = [
		'.',
		'./Include',
		'./PC'
	]

	defines = ["Py_NO_ENABLE_SHARED"]

	libs = ["python312"]
	if bld.env.DEST_OS != 'win32':
		libs += ['DL']
	else:
		libs += ['USER32', 'SHELL32']

	install_path = bld.env.LIBDIR

	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = "CONSOLE,5.01",
		idx      = bld.get_taskgen_count()
	)

